# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'strain in zz direction, eq.6
#'
#' details
NULL

#'shift of conduction band, eq. 7
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#'functions that returns InGaAsP parameters: a,c11,c12,ac,av,b for the given x,y
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#' function
#'
#' details
NULL

#'Eg for heavy holes with strain
#'
#' Bandgap with heavy holes effects
NULL

#'Eg for light holes with strain
#'
#' Bandgap with light holes effects
NULL

#' function
#' 
#' details
NULL

#' Conversion of Bandgap into photoluminescence (PL) wavelength in nm
#'
#' Eg into PL in nm
NULL

#' @param Eg bandgap in eV units
#' @return PL in nm as double
NULL

#' InGaAsP Strain in absolute units from X and Y
#'
#' Function use interpolation PQ_interp_a0
#'@export
eps_xy_f1 <- function(x, y) {
    .Call('ingaasp2rcpp_eps_xy_f1', PACKAGE = 'ingaasp2rcpp', x, y)
}

#' Unstrained bandgap Eg in eV from polynomial eq.3
#' 
#' Strain effects are not included, Eg in eV from polynomial eq.3
#'
#' @param x Ga molar fraction
#' @param y As molar fraction
#'
#'@export
PQ_Eg_unstrained <- function(x, y) {
    .Call('ingaasp2rcpp_PQ_Eg_unstrained', PACKAGE = 'ingaasp2rcpp', x, y)
}

#' Calculate Eg from X and Y
#'
#' Function checks whether light holes or heavy holes gives smaller bandgap
#'
#'
#' @export
PQ_Eg_XY <- function(x, y) {
    .Call('ingaasp2rcpp_PQ_Eg_XY', PACKAGE = 'ingaasp2rcpp', x, y)
}

#'lattice constant from eps_xy and for InP substrate
#'
#' details tbd
#'
#' @param eps_xy Strain in plane of material in absolute units
#' 
#' @return Lattice constant in nm units
#' @export
LatticeConst <- function(eps_xy) {
    .Call('ingaasp2rcpp_LatticeConst', PACKAGE = 'ingaasp2rcpp', eps_xy)
}

#' function
#' 
#' details
#' @export
PQ_Y_XStrain <- function(x, eps_xy) {
    .Call('ingaasp2rcpp_PQ_Y_XStrain', PACKAGE = 'ingaasp2rcpp', x, eps_xy)
}

#' function
#' 
#' details
func4root <- function(x) {
    .Call('ingaasp2rcpp_func4root', PACKAGE = 'ingaasp2rcpp', x)
}

#' function
#' 
#' details
#' @export
PQ_X_EgStrain <- function(Eg, eps_xy) {
    .Call('ingaasp2rcpp_PQ_X_EgStrain', PACKAGE = 'ingaasp2rcpp', Eg, eps_xy)
}

#' Convertsion of PL wavelength to bandgap in eV
#'
#' details tbd
#' @param PL photoluminescence wavelength in nm. See examples.
#' @return Bandgap Eg as double in eV units
#' @export
#' @examples
#' PL2Eg_f1(1200) # 1.033202 eV
PL2Eg_f1 <- function(PL) {
    .Call('ingaasp2rcpp_PL2Eg_f1', PACKAGE = 'ingaasp2rcpp', PL)
}

#' @export
Eg2PL_f1 <- function(Eg) {
    .Call('ingaasp2rcpp_Eg2PL_f1', PACKAGE = 'ingaasp2rcpp', Eg)
}

